var path = require('path');

module.exports = {
    root: {
        src: path.join(__dirname, '../src'),
        dest: path.join(__dirname, '../public/')
    },
    watchableTasks: ['ngTemplates', 'scripts', 'styles', 'iconfont', 'sprite', 'lint', 'ejs'],
    tasks: {
        browserSync: {
            // Taking the options from: https://www.browsersync.io/docs/options/
            // Serve files from the app directory
            server: {
                baseDir: "./public"
            }
            // Proxy through another webserver
            /*
            proxy: {
                target: "http://example.com"
            }*/
        },
        ejs: {
            src: 'templates',
            dest: '',
            extensions: ['ejs'],
			options: {
				ext: ".html"
			}
        },
        lint: {
            src: 'scripts',  //for watch folder
            extensions: ['js'],
            glob: ['scripts/**/*.js','!node_modules/**'], //relative to root.src
            eslint: {
                globals: [
                    'jQuery',
                    '$'
                ],
                envs: [
                    'browser',
                    'node'
                ]
            }
        },
        scripts: {
            src: 'scripts',
            dest: 'assets/js',
            input: ['main.js'],
            output: 'app.js',
            extensions: ['js']
        },
        styles: {
            src: 'styles',
            dest: 'assets/css',
            sources: [ 
                { input: 'styles.scss', output: 'styles.css'},
            ],
            extensions: ['scss','sass','css']
        },
        sprite: {
            src: 'images/',
            dest: 'assets/css/img/',
            cssDest: './src/styles',
            imgName: 'sprite.png',
            retinaImgName: 'sprite@2x.png',
            cssName: 'sprite.scss',
            extensions: ['png']
        },
        iconfont: {
            src: 'icons/',
            dest: 'assets/css/fonts/',
            template: 'icons/templates/webfont.template.css',
            cssDest: './src/styles',
            cssName: '_icons.scss',
            extensions: ['svg'],
            config: {
                fontName: 'icons', // required
                prependUnicode: true, // recommended option
                formats: ['svg', 'ttf', 'eot', 'woff', 'woff2'], // default, 'woff2' and 'svg' are available
                timestamp: Math.round(Date.now()/1000), // recommended to get consistent builds when watching files
                normalize: true,
                fontHeight: 500
            }
        },
        ngTemplates: {
            src: 'scripts/ng',
            dest: './src/scripts/ng',
            extensions: ['html'],
            output: 'templates.js',
            config: {
                module: 'NgCachedTemplate',
                templateHeader: '//Auto generated by `gulp ng-templates`\nimport angular from "angular";\n\n' +
                'let module = angular.module(\'<%= module %>\'<%= standalone %>,[]);\nmodule.run(["$templateCache", function($templateCache) {',
                templateBody: '$templateCache.put(\'<%= url %>\',\'<%= contents %>\');\n',
                templateFooter: '}]);\nexport default module.name;'
            }
        }
    }
};